---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver:
      customize:
        memory: 1024
      network:
      - ["forwarded_port", {guest: 8080, host: 8181}]
  - name: centos-6.5
    driver:
      customize:
        memory: 3048
      network:
      - ["forwarded_port", {guest: 8080, host: 8182}]
  - name: debian-7.2.0
    driver:
      customize:
        memory: 1024
      network:
      - ["forwarded_port", {guest: 8080, host: 8183}]
suites:
  - name: default
    run_list:
      - recipe[kitchen_jenkins::default]
    attributes: 
